[package]
name = "sdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
num-complex = "0.4.3"
radsort = "0.1.0"
grid = "0.9.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
